Randomization Params
Unity-Technologies/SynthDet pull request #26
Opened 2020-09-02 20:36 UTC by Saurav-D

Added SynthDet Randomization Param doc for public UnityGroceries - Synthetic dataset.

2020-09-09 15:49 UTC, JonathanHUnity commented on docs/UnityGroceriesSyntheticRandomizationParams.md
> +For public UnityGroceries - Synthetic dataset we generated nearly around 5k
```suggestion
For the UnityGroceries - Synthetic dataset we generated almost 5k
```
Should clarify if this means "almost" or "about" 5k images

2020-09-09 15:53 UTC, JonathanHUnity requested changes
This page should be linked from the rest of the documentation. Since the description of this specific dataset is in datasetinsights now, should we split this doc into two - one which describes the parameters and one which describes UnityGroceries - Synthetic?

2020-09-21 16:06 UTC, JonathanHUnity commented
@Saurav-D This is a really nice addition. Can we get this landed?

2020-09-30 18:00 UTC, Saurav-D commented
> @Saurav-D This is a really nice addition. Can we get this landed?

Sure. Sorry, I got off track.

2021-05-05 18:45 UTC, mkamalza commented
This PR was made for the original SynthDet project, which is now living in the SynthDet_Original branch. I am going to close this for now as the new master branch has a vastly different project.

2021-05-05 18:45 UTC, closed without merging